# invoice-app/templates/postgres/persistentvolume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "fullname" . }}-postgres-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/postgres"

