# invoice-app/templates/postgres/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # (base64 encoded value of "postgres")
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # (base64 encoded value of "postgres")
  POSTGRES_DB: a3ViZXJuZXRlc19kamFuZ28=  # (base64 encoded value of "kubernetes_django")

