# invoice-app/templates/redis/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}-redis-secret
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXM=  # (base64 encoded value of "redis")

