# invoice-app/templates/redis/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}-redis-service
spec:
  selector:
    app: {{ template "fullname" . }}-redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  clusterIP: None

