# invoice-app/Chart.yaml
apiVersion: v2
name: invoice-app
description: A Helm chart for the invoice application
version: 0.1.0

dependencies:

  - name: frontend
    version: 0.1.0
    repository: "file://./charts/frontend"

  - name: postgres
    version: 0.1.0
    repository: "file://./charts/postgres"

  - name: redis
    version: 0.1.0
    repository: "file://./charts/redis"

