# invoice-app/templates/frontend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-frontend
    spec:
      containers:
      - name: frontend
        image: chandan010101/fs
        ports:
        - containerPort: 80
        env:
        - name: WEBSOCKET_URL
          value: "ws://my-django-app-service:8888"
        volumeMounts:
        - name: frontend-data
          mountPath: /app/data
      volumes:
      - name: frontend-data
        persistentVolumeClaim:
          claimName: my-postgres-pvc

